### ISSUE TITLE
dropbear ssh keys not generated when making an fresh install of 7.2 (no upgrade)

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#100]
It seems that the generation of the ssh-keys for dropbear is inside the Package linuxmuster-linbo-common which is not present in 7.1 and 7.2
So the ssh client in lonbo does not start

Reference:
https://ask.linuxmuster.net/t/lmn-7-2-testing/9732/362

LG
Holger

**Comment by HappyBasher** [comment]
SSH keys should be in pem format so they can be converted to dropbear format.
