### ISSUE TITLE
images with a qcow2-size of ca 52 GB and bigger cannot be distributed via torrent because of an invalid metainfo file

### ISSUE THREAD

**Issue by lemertens** [linuxmuster/linuxmuster-linbo7#101]
qcow2 images, that exceed a  certain size (something between 50 GB and 56 GB) will have an invalid .torrent file ( error message : "....is really a metainfo file???") resulting in an unavailable torrent for this image.
 this can be fixed by using a higher piece-length when generating the .torrent file. 
as a hotfix i suggest doubling the piece length by  changing line 71 of 
/usr/sbin linbo-torrent 
from
``` if ctorrent -t  -u "http://$serverip:6969/announce" -s "$torrent" "$image" ; then ```
to
``` if ctorrent -t -l 524288 -u "http://$serverip:6969/announce" -s "$torrent" "$image" ; then ```

to raise the  qcow2's size limit to something around 100 GB. 
in the long run it might be worth considering to make the piece-length configurable

**Comment by HappyBasher** [comment]
Done.
