### ISSUE TITLE
rsync is looking in the wrong folder for .macct Files

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#102]
Hey Thomas,

me an d others got lots of messages lieke the following in /var/log/syslog

`Sep 29 13:24:56 server rsyncd[783508]: rsync on linbo/win10-lmg-intel.qcow2.macct from r154-pc10.bzpf.lan (10.17.154.10)
Sep 29 13:24:56 server rsyncd[783508]: building file list
Sep 29 13:24:56 server rsyncd[783508]: rsync: [sender] link_stat "win10-lmg-intel.qcow2.macct" (in linbo) failed: No such file or directory (2)
`
See here:
https://ask.linuxmuster.net/t/lmn-7-2-testing/9732/498

System is working correctly: seems to be an cosmetic Issue.

LG

Holger

**Comment by HappyBasher** [comment]
It's not a bug, it's a feature. ;-)
It is not intended to download the macct file to the client. When the client requests the macct file, it's a trigger for the server to set the machine account password for the client.
