### ISSUE TITLE
add linbo-remote parameters for postsync and prestart scripts

### ISSUE THREAD

**Issue by helgeschneider** [linuxmuster/linuxmuster-linbo7#108]
Da wir mit riesigen virtuellen Maschinen arbeiten waere es super, wenn wir mit linbo-remote nur einen postsync ausfuehren koennten, dann waere es bei kleinen Aenderungen moeglich, diese durch postsync zu pushen und das ohne neuen sync.

So koennte das aussehen:
**_linbo-remote -g jammy_123 -c postsync,start_** 

Denke da muss nur der sync-Teil von **_-c sync_** weg, aber irgendwas passt ja dann doch immer  nicht.
Wir wuerden das feiern. :)

**Comment by HappyBasher** [comment]
For easy manipulating the os filesystem postsync and prestart scripts should be executable per linbo-remote parameters on the client.

**Comment by HappyBasher** [comment]
Done in [Release 4.3.1](https://github.com/linuxmuster/linuxmuster-linbo7/releases/tag/v4.3.1).
