### ISSUE TITLE
kernel specified in start.conf ignored on efi systems

### ISSUE THREAD

**Issue by thoschi** [linuxmuster/linuxmuster-linbo7#110]
In our image we have 2 kernel installed - the ubuntu standard kernel and a kernel for surface devices.

We have 2 hardware classes defined, using the same base image.

Recently we realized that the kernel specified in the surface hardware class (boot/vmlinuz-surface and initrd.img-surface) is ignored and instead the standard kernel is booted.

**Comment by HappyBasher** [comment]
I'm afraid I can't reproduce. I have
```
Kernel = vmlinuz.old
Initrd = initrd.img.old
```
entered into the start.conf as an alternative kernel and taken into the grub configs with `linuxmuster-import-devices`. Then booted with
```
KernelOptions = quiet splash dhcpretry=5
```
and
```
KernelOptions = quiet splash dhcpretry=5 forcegrub warmstart=no
```
and both times the old kernel was booted correctly.

**Comment by HappyBasher** [comment]
Obviously a false report.
