### ISSUE TITLE
Orpahned linbocmd files are not cleaned up

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#111]
Hi @HappyBasher,

recently, I've noticed, that many clients boot to a disabled GUI in LINBO. Now, I have found the reason:
When linbo-cmd is run, but the client does not wake up, the linbocmd files are not cleaned up.
For example:
`linbo-remote -i test1 -c sync:1,halt -d -w 60`

If the client does not wake up, the file `/srv/bin/linbocmd/test1.cmd` with the content `disablegui` remains.

I guess this is a regression from previous refactorings.

**Comment by HappyBasher** [comment]
No this is  desired behaviour. If the client does not wake up I want that he executes the sync the next time he is powered on to ensure the latest image will be applied in any case. If you want to clean up commands of not waked up clients you have to script it yourself.

**Comment by HappyBasher** [comment]
Not a bug, works like expected.

**Comment by dorianim** [comment]
But it wasn‘t always like this, was it? I only saw this behavior recently.
How about adding a flag to linbo_cmd for this?

**Comment by HappyBasher** [comment]
It never worked differently. Why don't you start the command like this: `linbo-remote -p sync:1 -w0 -i client-01 && sleep 600 && rm -f /srv/linbo/linbocmd/*`? I think this is exactly what you want.
