### ISSUE TITLE
Wifi in OS not working when used in Linbo

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#113]
Hi @HappyBasher 

I just tried the new Linbo Wi-Fi functionality and got it to work without any problems :)
However, when Linbo is using the Wi-Fi, it stops working in the OS (PopOS). dmesg shows the following error:
```
[    ...] iwlwifi: probe of 0000:0x:00.0 failed with error -110
```
`x` is 4 or 1 depending on the device. I've tested on two platforms:
- Lenovo Yoga 11e (`iwlwifi-7260-17.ucode`)
- Lenovo E460 (`iwlwifi-7265D-29.ucode`)

Both show this behavior. As soon as I disable Wi-Fi in Linbo (by removing the according line from `/etc/linuxmuster/linbo/firmware`) the Wi-Fi works again in PopOS.

**Comment by HappyBasher** [comment]
So add `nowarmstart` to the linbo kernel options to initiate a cold reboot before os will be started. I think `kexec` has issues with loaded firmware.

**Comment by HappyBasher** [comment]
BTW, I do not think this a bug of Linbo.

**Comment by dorianim** [comment]
Thanks, I'll try that. Maybe, you could add that to the readme :)
