### ISSUE TITLE
build fails with currently available kernels

### ISSUE THREAD

**Issue by itkpeter** [linuxmuster/linuxmuster-linbo7#114]
The script build/conf.d/2_kernel-versions causes build process to fail because the current content of kernel.org does not return the expected kernel versions.
I had to change STABLE to "6.9" because 6.7 gets no more result with the KVERSIONS wget request.
Additionally the response for the mainline kernel 6.10 has to be grepped out, too.

**Comment by hermanntoast** [comment]
For me it helped to filter the output a bit more and append the dot to the kernel version filter:

https://github.com/linuxmuster/linuxmuster-linbo7/blob/b6bab138e2a9055e71934d1444b8fad5e05f9d0c/build/conf.d/2_kernel-versions#L12
`
KVERSIONS="$(wget -q https://kernel.org -O - | grep tarball | grep "linux-$STABLE\.\|linux-$LONGTERM\.\|linux-$LEGACY\." | grep -o "$STABLE.[0-9]*\|$LONGTERM.[0-9]*\|$LEGACY.[0-9]*")"`

**Comment by HappyBasher** [comment]
Fixed with https://github.com/linuxmuster/linuxmuster-linbo7/commit/772fcd6eac0b9d27992c68d8faf34db7bec9ae50.
