### ISSUE TITLE
include linbo_size_cache and linbo_size_disk into linbo_cmd

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#122]
Hi Thomas,

I wanted to fix https://github.com/linuxmuster/linuxmuster-linbo-gui/issues/95, but I can't find the new commands in `linbo_cmd`. Please add them to `linbo_cmd` since this is used for everything else as well.

Thanks :)

**Comment by HappyBasher** [comment]
With Linbo 4.3 you are able to use the mentioned commands. However, it is recommended to use the real commands instead.
