### ISSUE TITLE
ntfsresize seems to not work anymore (testet in 2.4.3)

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#25]
after cloning an NTFS Image into a bigger Partition linbo resets the partitionsize to the size of the initial Image Partition size.
Discussion here: 
https://ask.linuxmuster.net/t/partitionsgroesse-in-linbo-kann-nicht-geaendert-werden/8234/18

yours 
Holger

**Comment by garblixa** [comment]
Not an ntfsresize problem. ntfsresize works as expected after successful NTFS cloning.

Rather, the partitioning is changed so that it does not match the partitioning of the corresponding start.conf.
This affects both the NTFS partition and the cache partition, so regardless of the file system.

**Comment by garblixa** [comment]
Ich habe die Ursache gefunden.
Hier wird die Partitionierung zurückgesetzt:
linbo_cmd Zeile: 2503
```` 
   # restore gpt label                                                                      
    if fdisk -l "$disk" | grep -q "GPT"; then                                           
      local gptlabel="$bootdir"/gptlabel."$group"                                       
      if [ -s "$gptlabel" ]; then                                                       
        echo "Restoring gpt label from $(basename "$gptlabel")." | tee -a /tmp/linbo.log
        dd if="$gptlabel" of="$disk" bs=512 count=34 2>> /tmp/linbo.log             
      fi                                                                             
    fi                    
````
