### ISSUE TITLE
.info file of an image is not copied if it was not present before sync,

### ISSUE THREAD

**Issue by lemertens** [linuxmuster/linuxmuster-linbo7#28]
Whenever the .info -file of an image is missing linbo will download the image, unfortunately without downloading the .info file as well.
So on next sync, .info is missing again, and the image will be downloaded again, regardless of how actual the cached image is.
This will result in "always download" for
- new machines
- clients where cache partition are erased
- clients which are switched from cloop to qcow images

**Comment by HappyBasher** [comment]
Same as #29.
