### ISSUE TITLE
Add global.reg to linuxmuster-win

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#32]
Hi thomas,

I saw someone post this on ask:
How about moving the [global.reg](https://github.com/linuxmuster/linuxmuster-linbo7/blob/main/serverfs/srv/linbo/examples/win10.global.reg) into linuxmuster-win? This way, it will be on the client automagically and tjere is no need to copy it anymore.

Regards,
Dorian

**Comment by HappyBasher** [comment]
Good idea.
