### ISSUE TITLE
fullsync with ext4 Filesystems changed behavior

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#34]
Hello there,

earlier versions of linbo did not care for the partitionsize wehen syncing ext4 Filesystems (opposed to ntfs filesystems using partclone).
So it was possible to sync the Image created from a 40GB Partition to a 30 GB Partition.
Now this does not work anymore, as soon as linbo makes a "fullsync".
If linbo does an rsync sync it syncs the "big Image" without any problems to the "small" partition.
The Message is:
"Error: imagename.qcow2 (BITSIZEinK) is bigger than partition /dev/sda1 (BITSIZEinK)"
syncing is aborted after that.

yours Holger

**Comment by dorianim** [comment]
Hi Holger,

I think, this is intended behaviour. An imgale which is karger than the partition should not be synced.

**Comment by baumhof** [comment]
Hi Dorian,
i dont think so.
First: it did work in the Past
Second: the Datasize inside the Image is not larger than the destinationpartition but it was taken from a larger Partition. The Datasize is far less than the destinationpartitionsize.

yours Holger

**Comment by dorianim** [comment]
Hi Holger,

Hmm ok. I think, we have to discuss this internally :)

**Comment by dorianim** [comment]
... but you're right, backwards compatibility should probaply be preserved.
