### ISSUE TITLE
Move Build env to Ubuntu 22.04

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#42]
Hi @HappyBasher 

I am currently porting the GUI to Qt6. But there is a major problem: [Qt6 requires cmake 3.16](https://stackoverflow.com/questions/65356122/list-doesnt-recognize-subcommand-transform-error-in-cmake) and Ubuntu 18.04 only ships with 3.10.
So, in order to build, we need to migrate to at least Ubuntu 20.04 for building. 
Can this be done?

Regards,
Dorian

**Comment by HappyBasher** [comment]
Better build a statically build version. The next upgrade of the build environment is planned in sync with the server upgrade to 22.04.

**Comment by dorianim** [comment]
I am building a statically linked version. But when I build it on ubuntu 20.04 it does not run in linbo.

**Comment by dorianim** [comment]
We need to find some solution for this. Until this is solved, there can't be any updates to the gui.

**Comment by kiarn** [comment]
Hello @dorianim 

For this kind of updates, branch is a great tool in git : you can prepare a migration to qt6 on a separate branch and still be able to update the master branch under qt5.

Arnaud

**Comment by dorianim** [comment]
Hi Arnaud,

Unfortunately this is not possible. During the migartion, I did a lot of refactoring which would make it impossible to merge changes from master back into the new branch. In addition to that, many issues have been solved by cleaning up and restructuring the code. I don't have the time to manually port them back. 
(See: https://github.com/linuxmuster/linuxmuster-linbo-gui/pull/68 )

Regards, 
Dorian

**Comment by dorianim** [comment]
@HappyBasher What is holding this back? Is there anything that doesn't work on newer Ubuntu versions?

**Comment by kiarn** [comment]
@dorianim : just to understand, are you asking to upgrade all linuxmuster instances to 20.04 or only a special environment to build linbo ?

Upgrading all instances to 20.04 need some testing first, we must check that all soft ( webui, sophomorix, etc ... ) are working correctly on 20.04, that's why we planned in the last 2 dev-meeting to do this in april and jump the next major upgrade to 22.04.

**Comment by dorianim** [comment]
I just want to upgrade the [Linbo build environment](https://github.com/linuxmuster/linbo-build-docker) to Ubuntu 20.04. The Server and all other components are not affected at all.

**Comment by kiarn** [comment]
Ok ! :+1:

**Comment by HappyBasher** [comment]
I fear moving linbo build environment to 20.04 will cause issues on the server side on linbo (opentracker f.e.). I kept build env and server side always in sync so far. In the sense of a resource-saving approach, I suggest to use Qt5 version of linbo gui until we move the server to 20.04.

**Comment by HappyBasher** [comment]
until we move the server to 22.04.

**Comment by dorianim** [comment]
Could you please at least test it? Going back to Qt5 would involve serious effort.

**Comment by dorianim** [comment]
This migration has to be done anyway at some point...

**Comment by dorianim** [comment]
I am now using this: https://github.com/jwlawson/actions-setup-cmake to install a newer version of cmake, so resolving this is not so super urgent anymore.
It still has to be done at some point, tough.

**Comment by dorianim** [comment]
Now that it is almost released, we should target 22.04 instead.
