### ISSUE TITLE
Image status file timing

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#43]
Hi,

I just synced the host `3DD-maker1` at around 11:30. But the file `/var/log/linuxmuster/linbo/3DD-maker1_image.status` contains:
```
202201081617 applied: windows10_mlm_3D.cloop 202201031925
```
So, the date (20220108) is correct, but the time (1617) is incorrect. 

`ls -l` shows the correct time:
![image](https://user-images.githubusercontent.com/30153207/148642533-b439c6ad-1cf2-4be4-a351-8b72fcf18662.png)

What could be the reason for this? Is there any detailed information about the file format?

Regards,
Dorian

**Comment by HappyBasher** [comment]
The timestring is created with `date +%Y%m%d%H%M` (see linbo_cmd line 2481), so the only possibility for this phenomena is that the client does not have the right time.

**Comment by dorianim** [comment]
But shouldn't linbo care about the timng?

**Comment by HappyBasher** [comment]
Indeed linbo gets the time from the server already. I fear I don't understand what you mean.

**Comment by dorianim** [comment]
This means the problem is somewhere in linbo, so this issue should not be closed, and we should investigate this further.

**Comment by HappyBasher** [comment]
That should be reproducible otherwise it is not a bug.

**Comment by dorianim** [comment]
I can reproduce it. The time is always off by three hours. The minutes are fine, however. I will open a new issue for this.
