### ISSUE TITLE
MAX_UPLOADS linbo-bittorrent

### ISSUE THREAD

**Issue by teacherrust** [linuxmuster/linuxmuster-linbo7#45]
Hallo,

it would be helpful if in
/etc/default/linbo-bittorrent

MAX_UPLOADS=40
instead of
MAX_UPLOADS=4

cause, most of the clients are waiting for torrent and fall back to rsync. 
In our case (MAX_UPLOADS=40 or 80), it is faster to sync many clients. 

VG

**Comment by HappyBasher** [comment]
In the current linbo version >= 4 this setting is deprecated. Anyway, it is difficult to give default values for this setting, as it depends very much on the conditions on site. Everyone has to find the optimal setting for their system.
