### ISSUE TITLE
Allow to use -n without -c or -p

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#54]
https://github.com/linuxmuster/linuxmuster-linbo7/blob/069e8231fa7cad023c2707839ae9aad5b6741def/serverfs/usr/share/linuxmuster/linbo/linbo-remote.sh#L177

I think, it would make sense to allow usage of -n without -c or -p. In some cases I'd like to just start a client and ssh into linbo without executing anything. Same goes for -d.

Regards
Dorian

**Comment by HappyBasher** [comment]
This is not trivial and should be done later.

**Comment by HappyBasher** [comment]
https://github.com/linuxmuster/linuxmuster-linbo7/issues/85
