### ISSUE TITLE
auto partitioning should skip if disk layout matches intended partition table

### ISSUE THREAD

**Issue by Buster-de** [linuxmuster/linuxmuster-linbo7#59]
1st problem: partitioning should check if the current layout is the same as the intended layout and skip, otherwise this might result in a boot loop (had this one in the old GUI)

2nd problem: As an admin, who deploys a vast amount of computers in multiple rooms, you have computers that finish early and you want to reboot them to check if all is okay, while the majority of computers still need auto partioning enabled so you cant disable auto partitioning.

2nd wish: Give an option to manually skip auto partioning like you can cancel auto start of operating system
e.g. with an 3 sec countdown with abot and skip on pressing ESC button.

**Comment by HappyBasher** [comment]
Please split this issue. One issue for one item.
