### ISSUE TITLE
downloading linbo_gui leads to stalling Clients

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#60]
linbo 4.0.12 is running in my school on >100 Computers. In two Computerrooms (32 and 30 Clients) i am whitnessing the following Problem:
Some Clients stop booting with the Line "downloading linbo_gui..".
They do seed the torrent but they dont sync.
These Clients run win10 on sda1 (BIOS not UEFI) and start everytime trough grub with format:1,sync:1

Today i looked harder and connected to one stalling client per linbo-ssh
top showed a process of downloading linbo-gui (the last line visible on the LCD)

![linbo-gui-download](https://user-images.githubusercontent.com/3775116/158121403-c7c10cca-41a7-4947-a21f-10394c38e13a.png)

In the Picture it is PID 2137
The Computer just stopped there for over 30 Minutes.
Then i did kill -9 2137 while connected to the Client..
Immediately the Client resumed its work: formated sda1, started syncing sda1 and boot windows after sync sucessfully.

Yours
Holger

**Comment by baumhof** [comment]
Here are some stats on the Problem:
Room 1: 5 of 31 show "downloading" Problem (AMD Hardware win10 BIOS)
Room 2: 12 of 12 started show "Downloading" Problem there are 26 Clients in that room:14 did not start this Morning (INTEL Hardware win10 same as room 1)

Both rooms get woken up every morning 5 minutes apart with format:1,sync:1,start:1
In room 2 i had to start 14 Clients manually. None of those showed the Problem, but every Client startet this Morning with linbo-remote showed it.
So there could be a connection with Networktraffic.
The Clients did have their image localy: they did not need to download it trough torrent.

I "repaird" every of the 12 Clients in room 2 trough linbo-ssh and kill -9

Yours
Holger

**Comment by baumhof** [comment]
Stats for Today: 60 Clients startet, 12 stalled with downloading linbo-gui64

**Comment by HappyBasher** [comment]
Hopefully fixed with https://github.com/linuxmuster/linuxmuster-linbo7/commit/a496789451ebe125bc18c074899119ed6c597820.

**Comment by baumhof** [comment]
New Information: today the same 12 Clients stalled ... restart +sync does not help. Killing the mv command letzs them sync and start, only to stall on reboot. Today i tried additionally to rm the linbo_gui64....md5.bak
Tomorrow i will see, if that helps those 12 Clients.

**Comment by baumhof** [comment]
could not test 4.0.15 yet due to patching Problems.
Next try with 4.0.16 on Monday if patching works.

deleting /cache/linbo_gui64.???.bak after killing the mv command seemed to soften the Problem.
Fewer Clients were stricken by the Problem after deleting the .bak in Cache.

**Comment by HappyBasher** [comment]
Closed because of inactivity. Feel free to reopen it, if it is necessary.
