### ISSUE TITLE
auto partitioning should skip if disk layout matches intended partition table

### ISSUE THREAD

**Issue by Buster-de** [linuxmuster/linuxmuster-linbo7#62]
Auto partitioning should check if the current layout is the same as the intended layout and skip, otherwise this might result in a boot loop (had this one in the old GUI)

As an admin, who deploys a vast amount of computers in multiple rooms, you have computers that finish early and you want to reboot them to check if all is okay, while the majority of computers still need auto partioning enabled so you do not want to disable auto partitioning.

**Comment by HappyBasher** [comment]
This contradicts the original intention of autopartitioning to force a radical repair of the computer in any case if it is damaged by operating system lessons. Anyway an os sync is mandatory after an autopartitioning so a boot loop should not occur and has not been observed by us so far.
We will discuss this tomorrow in our meeting, but however, as long as this phenomenon does not affect any other user, nothing will happen in this regard.

**Comment by dorianim** [comment]
I'd like to have this feature as well. It would be nice if every computer would automatically partition itself when the disk layout in the start.conf is changed.

**Comment by Buster-de** [comment]
> This contradicts the original intention of autopartitioning to force a radical repair of the computer in any case

That would still work, just dont press the key to skip partitioning. But imagine you healed the computer and the display went in standby mode. Instead of pressing any key to end the black screen(saver), you press power switch (because you didn't notice it still running). Now the computer reboots and you have to wait another 30 minutes (partitioning, cache download, image copying) because all "repair" is done again. Imagine you do an unboxing of new computers, deploy the image and after that you want to run the latest firmware/bios updates as soon as possible. These installers have forced reboots you can't even cancel or delay. And you don't want to wait till all computers in that group have finished, so you could safely disable autopartitioning in start.conf.

**Comment by HappyBasher** [comment]
@dorianim This is something completely different and should be discussed in an own issue.

**Comment by HappyBasher** [comment]
@Buster-de To use autopartitioning to deploy a new computer is IMO completely senseless. I've never done this and I deployed thousands of them so far.

**Comment by HappyBasher** [comment]
Apart from that, I don't think it's a good idea to give the standard user the option to cancel autopartitioning. That presupposed that the user in this case knows exactly what he is doing. This will in the end give the admin more work due to operating errors and contradicts the higher-level principle to keep it simple for the user.

**Comment by HappyBasher** [comment]
`That would still work, just dont press the key to skip partitioning.`
Nope, if I implement an automatic to skip the autopartitioning in some case I need additiionally a switch to force it anyway if I want to keep the old behaviour. This is what I call wasteful use of volunteer resources.

**Comment by HappyBasher** [comment]
Apart of that, Putting effort into customizing a software to avoid operating errors originally caused by an activated screensaver seems to me to be more than questionable.

**Comment by Buster-de** [comment]
> To use autopartitioning to deploy a new computer is IMO completely senseless. I've never done this and I deployed thousands of them so far.

And the world had deployed millions of computers without linbo. What is the point so far? Okay, i never thought i had to argument about saving time in processes using a software whose whole intend is to save time for IT staff. It is okay for you to not use auto partitioning, that's okay for me, but don't expect all users to follow your procedures. That makes that wish not invalid or "senseless". What is senseless about it?

1. Unbox computer
2. scan barcdodes for MAC and inventory software
3. put computers and MAC into linbo webgui CSV editor into a group for autopartitioning and ready to go image.
4. place computers in class rom and poweron as you go
5. walk around to check "repaired" computers, log in and install bios/firmware updates. **reboot**
6. repeat step 5 until all computers are ready for end users

> This is what I call wasteful use of volunteer resources.

If that is an issue, then say it so, but don't argue that the feature request is obsolete or invalid. Maybe at some point one person will grab that issue and provide a solution. But if this is the environment people/ideas new to the community get treated, i'd reconsider efforts.

The screensaver was only one example to provide a better understanding. I can imagine many more situations where having auto partitioning enabled at all times can be helpful and yet at some point I want to skip it.

**Comment by HappyBasher** [comment]
autopartitioning is not made for initial deploy and therefore the wrong tool for it. I only need to partition my new computers once. After they are registered I type `linbo-remote -p format,sync:1,start:1 -r r100` and press [ENTER] on the server console, power them on and go for a coffee. When I return the os login waits for me.

**Comment by Buster-de** [comment]
But it could be a tool to use for this without having to use servers console. As i said, not everybody follows your procedures. We are several people in IT team and we share part of the tasks when we have to deploy a batch of computers. Powering them on via WoL needs them to have BIOS/UEFI settings previously deployed too.

**Comment by dorianim** [comment]
I agree that this is not the intended use case for autopartitioning. In lmn 7.1 the webui got a new plugin called linbo-sync. It can be used to control linbo-remote from the webui. 
It also allows to schedule a partitioning for the next boot of a PC.
As far as I understand it, that should solve your Issue.

**Comment by HappyBasher** [comment]
We will not work on this. The reasons have already been explained.
