### ISSUE TITLE
Featur Request: delete .cloop in Cache

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#65]
Hi there,
there will be a lot of People upgrading from linbo 2.x to linbo 4.x and all of them will have the same issue:
if these switch from cloop to qcow2 there will be a cloop in the cache on the Client.
We can now ether write in the upgrade notes to partition the Client or we might catch that Problem (with cache full since there will betwo Images: cloop and qcow2) by letting linbo check if there is a *.cloop in cach and delete it prior to downloading the new qcow2.

Just a sugesstion :-)

Yours 
Holger

**Comment by HappyBasher** [comment]
Automatic deletion of files is IMO no good idea. There may be circumstances where this is not desirable. Linbo >= 4.0.17 will cancel download, if the cache runs out of space. It should be documented that admins have to use `initcache` if they change the image name to ensure there is enough space in cache.

**Comment by HappyBasher** [comment]
Won't fix, see above.
