### ISSUE TITLE
Linbo does download Image twice

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-linbo7#69]
It seems that clients download qcow2 image twice when specifying torrent as download method.

First the download happens via rsync, then it gets downloaded again via torrent:

![grafik](https://user-images.githubusercontent.com/26460239/161995488-9f98bc46-ffdf-4912-a001-e72312de4cbf.png)
![grafik](https://user-images.githubusercontent.com/26460239/161995534-715a1eae-a7b2-4d91-8961-943f8a4e1708.png)
![grafik](https://user-images.githubusercontent.com/26460239/161995550-09007f7e-a25b-4b6d-b1eb-e422538286c1.png)
![grafik](https://user-images.githubusercontent.com/26460239/161995576-30ab6275-5721-4565-803f-13581026c2b4.png)

Tell me if you can reproduce this issue or need further information.

**Comment by HappyBasher** [comment]
Sorry, I don't see that qcow2 images are downloaded twice. Also I never observed this on my systems.

**Comment by PLanB2008** [comment]
Well If you take a look at screenshot one you can clearly see the client is getting the image file via rsync:

![grafik](https://user-images.githubusercontent.com/26460239/162389530-5acca3bf-6558-4f7a-a915-183a62ba6354.png)

I assume this should download all file except the image.

After this is received the download of the image via torrent begins:
![grafik](https://user-images.githubusercontent.com/26460239/162389619-f64d20d2-76ad-42ac-90cf-108da0c7fe81.png)


Either this is what happens or it takes 10 minutes to receive torrent, desc info and regpatch.

**Comment by HappyBasher** [comment]
Closed because of inactivity.
