### ISSUE TITLE
Don't download control file from github

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#76]
https://github.com/linuxmuster/linuxmuster-linbo7/blob/c4f16304149931759b206bb0b41f0d61a549d6ef/get-depends.sh#L16

Why are you downloading the file? Is there a reason not to take the local one?

**Comment by HappyBasher** [comment]
How can a local file be accessed in the build env?

**Comment by HappyBasher** [comment]
Yes, this pretty useless.

**Comment by HappyBasher** [comment]
Fixed in [b3b8b75](https://github.com/linuxmuster/linuxmuster-linbo7/commit/b3b8b75ad069efa20f24f6445fa827e1d2c704cb).
