### ISSUE TITLE
Python deprecation warning with Linbo 4.0.29-0 while WOL with linbo-remote

### ISSUE THREAD

**Issue by foer** [linuxmuster/linuxmuster-linbo7#79]
Good morning.

Starting with linbo 4.0.29-0 there is a python cryptography warning while waking up Clients with WOL over linbo-remote:

```
[root@server:/etc/linuxmuster/sophomorix/default-school]$ linbo-remote -i 10.16.1.50 -w0
###
### linbo-remote (6206) start: Do 21. Jul 09:06:55 CEST 2022
###

Trying to wake up:
 hp-client-test ... /usr/local/lib/python3.6/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
/usr/local/lib/python3.6/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Sending magic packet to 255.255.255.255:9 with <MACADDRESS>

###
### linbo-remote (6206) end: Do 21. Jul 09:06:56 CEST 2022
###


```
Neverless WOL ist working.

Dominik

**Comment by kiarn** [comment]
Hello @foer,

Which Version of paramiko do you have ? ( `pip3 show paramiko` )
It should be at least 2.10.1.

Arnaud

**Comment by foer** [comment]
Hallo @kiarn Arnauld,

> Which Version of paramiko do you have ? ( `pip3 show paramiko` )

```
[root@server:~]$ pip3 show paramiko
Name: paramiko
Version: 2.10.1
Summary: SSH2 protocol library
Home-page: https://paramiko.org
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /usr/local/lib/python3.6/dist-packages
Requires: bcrypt, cryptography, pynacl, six
Required-by:
```
Dominik

**Comment by kiarn** [comment]
Ok. I also have version 3.1 of cryptography on my system ( without any error in linbo-remote ).

**Comment by foer** [comment]
I figured it out. The problem is that the cryptography lib is at Version 37.0.3 and depends on python 3.10 with is to new for ubuntu 18.04 which ships python 3.6. The cryptography lib was installed with one of the last WebUi-Versions. I haven't looked in the linbo code, but it can be assumed, that the new version also needs the cryptography lib and triggers that error that way.

@kiarn: You've maybe manually installed an older Version of the cryptography lib, that's why the error doesn't show up in your installation.
  
I`ve downgraded cryptography to Version 36.0.2 which is the last Version for python 3.6 and the error is gone.

`pip3 install cryptography==36.0.0.2`

The whole situation show's exactly why i really hate installing python packages with pip. It's not the first time that those packages mess up with an older operation system like ubuntu.

Dominik
