### ISSUE TITLE
poor download rates with newer Intel I219-V NICs on kernel 5.10.x

### ISSUE THREAD

**Issue by itkpeter** [linuxmuster/linuxmuster-linbo7#80]
I'm trying to get a brand new Lenovo ThinkPad E15 Gen 4 with an Intel "I219-V (16)" (8086:1a1f) to run with LINBO.
The kernels in linbo versions prior v4 don't even recognize the NIC and linbo stops with choice [1] to reboot or [2] to shutdown.

The 5.10.x kernel of linuxmuster-linbo7 v4.0.0~0rc5 (from lmn7-testing repo) recognizes the NIC, but is not able to retrieve data from the server until I do the PXE boot with an arbitrary usb key plugged into an USB port.
Without plugged usb the network connectivity stops at the moment when trying to download a file from the server.
With plugged usb the download speed from server is about 10MB/s while upload speed is >100MB/s.

It seems to be a known kernel issue:
https://bugs.launchpad.net/ubuntu/+source/linux-oem-5.10/+bug/1930754
https://bugzilla.kernel.org/show_bug.cgi?id=213377
https://bugzilla.kernel.org/show_bug.cgi?id=213651

All mentioned workarounds like pcie_aspm=off didn't work with linbo.
It seems to be fixed with kernel version 5.15. Could the linbo-kernel be updated?

**Comment by HappyBasher** [comment]
Please upgrade to v4.0.29.

**Comment by itkpeter** [comment]
I'm on a LMN 7.0 production system and got the linbo v4 via pinning on testing repo.
Could you please explain how to include linbo v4.0.29 without too much change to the rest of the system?

**Comment by HappyBasher** [comment]
You can get support here: https://ask.linuxmuster.net/
