### ISSUE TITLE
sync cache on start deletes kernel in cache Partition

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#81]
Hi there,

it seems like linbo is deleting the kernel in the cache Partition, when "sync cache on startup" is set in the start.conf.GROUP as described in this thread:
https://ask.linuxmuster.net/t/nach-netzwerkboot-kein-boot-von-der-festplatte-mehr/9213/8
Yours 
Holger

**Comment by HappyBasher** [comment]
Fixed with https://github.com/linuxmuster/linuxmuster-linbo7/commit/197f7cc0cc8d0de37be637ee4b859bf917ae7f88.
