### ISSUE TITLE
.macct file will not be created correctly if imagename contains dots

### ISSUE THREAD

**Issue by delacroix0815** [linuxmuster/linuxmuster-linbo7#82]
Hello everyone,

i discovered when creating a new image with dots, the directory name containing the imagename gets cut off at the first dot during the rsync-post-upload process, e.g.:

ubuntu-1804-3.5-1.qcow results in that line in /srv/linbo/log/rsync-post-upload.log:

```
/usr/share/linuxmuster/linbo/rsync-post-upload.sh: Zeile 114: /srv/linbo/images/ubuntu-1804-3/ubuntu-1804-3.5-1.qcow2.macct: Datei oder Verzeichnis nicht gefunden
chmod: Zugriff auf '/srv/linbo/images/ubuntu-1804-3/ubuntu-1804-3.5-1.qcow2.macct' nicht möglich: Datei oder Verzeichnis nicht gefunden
```
When a new Image with no dots in the name is created, e.g. ubuntu-1804-3-5-1.qcow, the .macct is created and uploaded correctly into /srv/linbo/images/ubuntu-1804-3-5-1/ubuntu-1804-3-5-1.qcow2.macct. 

Almost the same issue was fixed already in https://github.com/linuxmuster/linuxmuster-linbo7/commit/7f15ee4df77bee57933129f458e80992c4082d46 but it looks like that adaption also must be inserted into /usr/share/linuxmuster/linbo/rsync-post-upload.sh to make the .macct creation & upload work.

See the original thread on ask.linuxmuster.net here: https://ask.linuxmuster.net/t/macct-datei-wird-beim-erstellen-des-images-nicht-angelegt-lmn-7-1-linux-image/9179/2

Greets,
Chris

**Comment by HappyBasher** [comment]
Finally fixed in v4.0.36.
