### ISSUE TITLE
FR: download linbo GUI theming files

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#83]
The linbo gui has the ability to be themed since a few versions. The required code was never ported to Linbo 7 though. See: https://github.com/linuxmuster/linuxmuster-linbo/pull/186

Would be nice to have that included :)

Documentation for the theming is available here: https://github.com/linuxmuster/linuxmuster-linbo-gui/wiki/Theming

We could also discuss the location of the files before this is implemented. What d you think (also @kiarn @PLanB2008 )?

**Comment by PLanB2008** [comment]
Ahhh I was wondering why this is not working anymore. This should be fixed. 

The location is okay in my opinion. Maybe we should do something like /srv/linbo/icons/custom ... I was thinking about this when I added some custom OS Icons to an installation

**Comment by PLanB2008** [comment]
Ya I see the benefits of your approach. This case we could easily have multiple themese. +1 for this approach

**Comment by HappyBasher** [comment]
I think the gui related stuff should be filed under `/srv/linbo/gui` to have it properly separated from plain linbo. So the linbo_gui package may manage this subdirectory independently. What do you think about that?

**Comment by HappyBasher** [comment]
So there could be also an init hook directory `linbofs.init.d` for instance, which will be packed into linbofs by `update-linbofs`and sourced on boot.

**Comment by dorianim** [comment]
That is a great idea! Then I could package the scripts for linbofs.init.d in the `linbo_gui64_7.tar.lz` and manage them independently.

**Comment by dorianim** [comment]
Then we also have to move `/srv/linbo/icons` to `/srv/linbo/gui/icons`, but I think, that's fine.

**Comment by kiarn** [comment]
> Then we also have to move `/srv/linbo/icons` to `/srv/linbo/gui/icons`, but I think, that's fine.

Ok, then I have to adapt this in the Webui.

**Comment by dorianim** [comment]
I'd prefer to do this in lmn 7.2
Otherwise, I have to implement everything twice in the GUI.

**Comment by HappyBasher** [comment]
> I'd prefer to do this in lmn 7.2

Yep, we should do it for lmn 7.2 / linbo 4.1.

**Comment by dorianim** [comment]
So if we all agree to do it like that, we can start to implement it :)
@PLanB2008 you have the last word

**Comment by HappyBasher** [comment]
> That is a great idea! Then I could package the scripts for linbofs.init.d in the linbo_gui64_7.tar.lz and manage them independently.

Nope. The init stuff has to be available on boot. So to pack it in the archive is pretty useless. The future linbo_gui package unpacks its content like that:
```
└── srv
    └── linbo
        └── gui
            ├── icons
            ├── linbofs.init.d
            ├── linbo_gui64_7.tar.lz
            └── themes
```

**Comment by dorianim** [comment]
And the linbofs.init.d will then be put into linbofs?

**Comment by HappyBasher** [comment]
Yep. But if go deeper into it I see that is also thinkable, that linbo.sh invokes gui scripts after downloading and unpacking the gui archive. It does not have to be in init.sh.

**Comment by dorianim** [comment]
In theory, this could also simply be done by the gui itslef, we don't really need extra scripts for this.

**Comment by HappyBasher** [comment]
For sure, the gui can do this itself on startup.

**Comment by dorianim** [comment]
Ok, so now we know how it'll be don in 7.2 but could you include the downloading like in 7.0 into 7.1? Otherwise theming does not work in the current stable version.

**Comment by HappyBasher** [comment]
Ok, I'll fix this in 4.0 and main branches. In fact the only task is to keep the icons folders in sync.

**Comment by dorianim** [comment]
Well, technically we don't need to download the whole icons folder, only the used ones and the used theme file.

**Comment by HappyBasher** [comment]
Fix: https://github.com/linuxmuster/linuxmuster-linbo7/commit/4afe1e4b00ab38e4b91336e6d258f0436fa82183

**Comment by dorianim** [comment]
We decided, that the linbo client will download the folder on boot if configured.

**Comment by HappyBasher** [comment]
To combine this:
* the linbo client syncs the server's gui folder _/srv/linbo/gui_ to _/cache/gui_
* including only icons and theme defined in start.conf
Right?

**Comment by dorianim** [comment]
Yes

**Comment by HappyBasher** [comment]
So, how is theme defined in _start.conf_?

**Comment by dorianim** [comment]
I think, the best would be to have 
```
[Linbo]
...
Theme=MyTheme
```
Where MyTheme will be in `/srv/linbo/gui/themes/MyTheme/`

**Comment by HappyBasher** [comment]
Theming files are downloaded to _/cache/gui_  using the structure mentioned above. On an unpartitioned client, which has no cache partition, the files will be downloaded to _/tmp/gui_.  Note: At runtime, the GUI will find the corresponding files under /icons and /themes.

**Comment by dorianim** [comment]
So I can just always use `/icons` and `/themes`?
I'll implement this in the GUI once there is a package available for testing :)

**Comment by HappyBasher** [comment]
Yes, then it is the same whether with or without cache.
