### ISSUE TITLE
Issue using linbo sync from grub menu

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-linbo7#87]
When using linbo new and start option from grub menu, the process stops at

„Checking filesystem Consisteny“  

and does not proceed any further. When using the option from linbo gui or linbo-wrapper via ssh, everything works as expected.

I dont know if this is also tied to some hardware or a general problem. Could you have a look into this?

**Comment by HappyBasher** [comment]
Sorry, cannot reproduce this. Works for me as expected.

**Comment by HappyBasher** [comment]
Closed due to long time of inactivity. Feel free to reopen if necessary.
