### ISSUE TITLE
Add salt to password hash

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#90]
Hi @HappyBasher 

the password is stored as a plain SHA hash. This is not good enough, as it can be easily checked against a known hash database.

For example, the hash of "Muster!":
```
> echo -n 'Muster!' | sha256sum
2a3a100d193d125752b42e97976963630b9d2d11513df94a235b5c6d3da53e46
```
Enter it over [here](https://md5decrypt.net/en/Sha256/) and get the plaintext.
 
Please at least add a salt to the password :)
It would also make sense to hash it several times (eg. 1000 times).

**Comment by HappyBasher** [comment]
HI @dorianim!

It's true, a plain hash isn't secure enough. But do you know a procedure to  authenticate with a salted password locally offline without having also the plain salt stored locally? Hashing severall times is not secure as well, as long as you deliver the unhashing algorithm with linbofs together with the password hash locally. To make it really safe we need the server, to do the password check not locally. But we agreed to do the authentication offlne.

**Comment by dorianim** [comment]
What we should do is this:
- generate a random salt (`s`) 
- hash (`password+s`) 1000 times
- put (`final_hash + s`) into linbofs

This will make it possible to check the hash, but impossible to brute force the hash in finite time.
We cannot make it completely secure, but we can make it so hard that it is impossible to crack it within a relevant time, and that's what this method does.

**Comment by HappyBasher** [comment]
Ok, thanx. I'll take a look at it.

**Comment by dorianim** [comment]
Simple example:

```bash
#!/bin/bash

if [ -z "$1"  ]
then
  echo "Usage: $0 <password>"
  exit 1
fi

SALT=$(cat /dev/urandom | head -c 5 | base64)
HASH=$(echo -n "$1$SALT" | sha256sum | awk '{ print $1 }')

for i in {0..1000}
do
  HASH=$(echo -n $HASH | sha256sum | awk '{ print $1 }')
done

echo $HASH$SALT
```

However, we might wanna go with less than 1000 times, it's kinda slow. 100 should also be fine.

**Comment by HappyBasher** [comment]
Uses now argon2 for password hashing.
