### ISSUE TITLE
Technical debt regarding gui

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo7#91]
Hi @HappyBasher 

I have two suggestions to consolidate some things before the linbo 7.2 release:

### gui files
[here](https://github.com/linuxmuster/linuxmuster-linbo7/issues/83#issuecomment-1259355610_) you suggested consolidating the directory structure to this:
```
└── srv
    └── linbo
        └── gui
            ├── icons
            ├── linbo_gui64_7.tar.lz
            └── themes
```

Do you still want to do that? I think, it would make a lot of sense!
It could also be done in linbofs, so the icons and themes folders are not in `/` but in `/gui`.

### gui config
We could put the gui config parameters in start.conf into a separate `[gui]` section. I think, this would make the start.conf clearer and easier to manage.

What do you think?

**Comment by HappyBasher** [comment]
The gui structure on the server is already implemented. For compatibility old and new structure are currently supported.
I'm not enthusiastic about the other suggestions. They will cause a lot of refactoring due to significant change of start.conf structure.

**Comment by dorianim** [comment]
> They will cause a lot of refactoring due to significant change of start.conf structure.

Ok
