### ISSUE TITLE
Cannot download linbo_gui due to faulty network status detection

### ISSUE THREAD

**Issue by gber** [linuxmuster/linuxmuster-linbo7#93]
Booting LinuxMuster LINBO over PXE on an unregistered client fails with the following error:

    Fatal: Cannot read network infos. Continuing offline.

When adding the new client to the WebUI first it receives the configured IP address and hostname via DHCP and networking is working fine. Yet, downloading the GUI fails with the above error. This seems similar to #40.

I am using linuxmuster-linbo7 4.0.44.

**Comment by HappyBasher** [comment]
Closed due to inactivity. Feel free to reopen if necessary.

**Comment by gber** [comment]
I have retried this with linuxmuster-linbo7 4.0.44 against a fresh installation of a LinuxMuster v7.1 server. The problem is that the client cannot download its `start.conf` here: https://github.com/linuxmuster/linuxmuster-linbo7/blob/v4.0.46/linbofs/init.sh#L598

The network is up and configured correctly via DHCP, the server can be pinged but rsync connections cannot be established:
![lm-client-network](https://github.com/linuxmuster/linuxmuster-linbo7/assets/1668189/6806200a-061e-4b99-bcac-264039df1b91)

However, rsyncd is listening on the server and I can pull the `start.conf` to the Admin PC which is on the exact same subnet:

```
lmadmin@lm-adminpc:~$ /sbin/route -n
Kernel-IP-Routentabelle
Ziel            Router          Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.0.254      0.0.0.0         UG    100    0        0 enp1s0
10.0.0.0        0.0.0.0         255.255.0.0     U     100    0        0 enp1s0
lmadmin@lm-adminpc:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:ca:79:c2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.10/16 brd 10.0.255.255 scope global noprefixroute enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::5aa0:9e48:372e:d38e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
lmadmin@lm-adminpc:~$ rsync root@10.0.0.1::linbo/tmp/start.conf_r101-pc10 start.conf
lmadmin@lm-adminpc:~$ 
```

So there is an issue with the network setup on the client.
