### ISSUE TITLE
Cannot obtain the correct start.conf

### ISSUE THREAD

**Issue by gber** [linuxmuster/linuxmuster-linbo7#94]
Due to #93 I've created a custom LINBO ISO for a group following the instructions at https://wiki.linuxmuster.net/community/anwenderwiki:linbo:linbo_boot_cd_erstellen

    /usr/share/linuxmuster/linbo/make-linbo-iso.sh ubuntu-20-04-muster-client

This boots into the LINBO GUI however it does not seem to contain or download the correct `start.conf` and displays the following error:

    No Operating system configured in start.conf

I am using linuxmuster-base7 7.1.21-0 and linuxmuster-linbo7 4.0.44-0.

**Comment by gber** [comment]
This seems similar to the issue reported in: https://ask.linuxmuster.net/t/no-operating-system-configured-in-start-conf/9206 However, the workaround there with changing the symlink does not work for me.

**Comment by HappyBasher** [comment]
The mentioned howto is outdated. The current iso file is always available under `/srv/linbo/linbo.iso` and has not to be created manually. Please obtain support in [https://ask.linuxmuster.net](https://ask.linuxmuster.net).

**Comment by HappyBasher** [comment]
Closed due to inactivity. Feel free to reopen.
