### ISSUE TITLE
Synaptics touchpad HP Probook 440 G7 does not work in linbo GUI

### ISSUE THREAD

**Issue by franknaumann** [linuxmuster/linuxmuster-linbo7#96]
Hi,
I tested a Ubuntu-linbo-Client on my HP Probook 440 G7 and in the linbo GUI the touchpad does not work, but in the ubuntu OS it does work. 

Here the config from /proc/bus/input/devices:
I: Bus=0018 Vendor=06cb Product=cdeb Version=0100
N: Name="SYNA30A5:00 06CB:CDEB Touchpad"
P: Phys=i2c-SYNA30A5:00
S: Sysfs=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-SYNA30A5:00/0018:06CB:CDEB.0001/input/input12
U: Uniq=
H: Handlers=mouse1 event9 
B: PROP=5
B: EV=1b
B: KEY=e520 10000 0 0 0 0
B: ABS=2e0800000000003
B: MSC=20

When I search for drivers on HP I found only windows:
Synaptics FS7600 WBF Touch Fingerprint Driversystem software
https://support.hp.com/ch-de/drivers/selfservice/swdetails/hp-probook-440-g7-notebook-pc/29090063/swItemId/ob-298564-1?source=google&channel=cpc&adcampaign=OLS-DE-PS-Goo-Pmax-Baseline-LE-Promotions&addisttype=x&kw=&adid=&gad=1&gclid=CjwKCAjwqZSlBhBwEiwAfoZUIKmNl5UDH0eipk8olUFtjjlGObMwQGxrZlUCyFfINGgLUVz_bCPMfhoCpkIQAvD_BwE&gclsrc=aw.ds

Can you take the driver into one of the next releases?

Thanks in advance and kind regards,
Frank

**Comment by HappyBasher** [comment]
Closed because of inactivity.
