### ISSUE TITLE
Fehler in linbo_patch_registry bein Windows 7

### ISSUE THREAD

**Issue by Markus1301** [linuxmuster/linuxmuster-linbo7#99]
Siehe Threat:
https://ask.linuxmuster.net/t/linbo-regpatcher-ab-4-0-13/8660/31

Problem: Wir haben noch über 100 Windows 7 Rechner an der Schule. Dadurch dass in 
linbo_patch_registry überprüft wird, ob in einer reg Datei services klein geschrieben ist und falls das so ist, wird servives zu Services.

Nun ist es so, dass bei Windows 7 tatsächlich in der Registry services klein geschrieben wird. Dies führt dazu, dass die beiden Zeilen in den reg Dateien ... \CurrentControlSet\services\Tcpip... nicht ausgeführt werden, weil er \CurrentControlSet\Services\Tcpip... daraus macht.

Dies führt dazu, dann nun alle Windows 7 Rechner "in der Systemsteuerung" den selben Namen haben. Nämlich den Namen des Rechners von dem geklont wurde.

Das macht Probleme!

**Comment by HappyBasher** [comment]
Fixed in 6fdeb7a58f85bd2af2fadd972902755ff7c832b2: Removed correction of registry key paths from regpatcher, adjusted reg file examples accordingly.

**Comment by HappyBasher** [comment]
Fixed.
